// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/sensor.proto

package nepulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryPayload is a single sensor frame emitted by a mobile client.
type TelemetryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AccX          float32                `protobuf:"fixed32,4,opt,name=acc_x,json=accX,proto3" json:"acc_x,omitempty"`
	AccY          float32                `protobuf:"fixed32,5,opt,name=acc_y,json=accY,proto3" json:"acc_y,omitempty"`
	AccZ          float32                `protobuf:"fixed32,6,opt,name=acc_z,json=accZ,proto3" json:"acc_z,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,7,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_proto_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_proto_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPayload) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryPayload) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TelemetryPayload) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TelemetryPayload) GetAccX() float32 {
	if x != nil {
		return x.AccX
	}
	return 0
}

func (x *TelemetryPayload) GetAccY() float32 {
	if x != nil {
		return x.AccY
	}
	return 0
}

func (x *TelemetryPayload) GetAccZ() float32 {
	if x != nil {
		return x.AccZ
	}
	return 0
}

func (x *TelemetryPayload) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// IngestResponse is returned once, when the client half-closes the stream
// (client-streaming RPC semantics: N requests in, 1 response out).
type IngestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount    int64                  `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	AcceptedCount    int64                  `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	DroppedCount     int64                  `protobuf:"varint,3,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"`
	FirstTimestampMs int64                  `protobuf:"varint,4,opt,name=first_timestamp_ms,json=firstTimestampMs,proto3" json:"first_timestamp_ms,omitempty"`
	LastTimestampMs  int64                  `protobuf:"varint,5,opt,name=last_timestamp_ms,json=lastTimestampMs,proto3" json:"last_timestamp_ms,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetReceivedCount() int64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *IngestResponse) GetAcceptedCount() int64 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestResponse) GetDroppedCount() int64 {
	if x != nil {
		return x.DroppedCount
	}
	return 0
}

func (x *IngestResponse) GetFirstTimestampMs() int64 {
	if x != nil {
		return x.FirstTimestampMs
	}
	return 0
}

func (x *IngestResponse) GetLastTimestampMs() int64 {
	if x != nil {
		return x.LastTimestampMs
	}
	return 0
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_sensor_proto protoreflect.FileDescriptor

const file_proto_sensor_proto_rawDesc = "" +
	"\n" +
	"\x12proto/sensor.proto\x12\anepulse\"\xcb\x01\n" +
	"\x10TelemetryPayload\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x13\n" +
	"\x05acc_x\x18\x04 \x01(\x02R\x04accX\x12\x13\n" +
	"\x05acc_y\x18\x05 \x01(\x02R\x04accY\x12\x13\n" +
	"\x05acc_z\x18\x06 \x01(\x02R\x04accZ\x12!\n" +
	"\ftimestamp_ms\x18\a \x01(\x03R\vtimestampMs\"\xf5\x01\n" +
	"\x0eIngestResponse\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x03R\rreceivedCount\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\x03R\racceptedCount\x12#\n" +
	"\rdropped_count\x18\x03 \x01(\x03R\fdroppedCount\x12,\n" +
	"\x12first_timestamp_ms\x18\x04 \x01(\x03R\x10firstTimestampMs\x12*\n" +
	"\x11last_timestamp_ms\x18\x05 \x01(\x03R\x0flastTimestampMs\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status2Z\n" +
	"\x0fTelemetryIngest\x12G\n" +
	"\x0fStreamTelemetry\x12\x19.nepulse.TelemetryPayload\x1a\x17.nepulse.IngestResponse(\x01B\x1aZ\x18ne-pulse/proto;nepulsepbb\x06proto3"

var (
	file_proto_sensor_proto_rawDescOnce sync.Once
	file_proto_sensor_proto_rawDescData []byte
)

func file_proto_sensor_proto_rawDescGZIP() []byte {
	file_proto_sensor_proto_rawDescOnce.Do(func() {
		file_proto_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sensor_proto_rawDesc), len(file_proto_sensor_proto_rawDesc)))
	})
	return file_proto_sensor_proto_rawDescData
}

var file_proto_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sensor_proto_goTypes = []any{
	(*TelemetryPayload)(nil), // 0: nepulse.TelemetryPayload
	(*IngestResponse)(nil),   // 1: nepulse.IngestResponse
}
var file_proto_sensor_proto_depIdxs = []int32{
	0, // 0: nepulse.TelemetryIngest.StreamTelemetry:input_type -> nepulse.TelemetryPayload
	1, // 1: nepulse.TelemetryIngest.StreamTelemetry:output_type -> nepulse.IngestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sensor_proto_init() }
func file_proto_sensor_proto_init() {
	if File_proto_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sensor_proto_rawDesc), len(file_proto_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sensor_proto_goTypes,
		DependencyIndexes: file_proto_sensor_proto_depIdxs,
		MessageInfos:      file_proto_sensor_proto_msgTypes,
	}.Build()
	File_proto_sensor_proto = out.File
	file_proto_sensor_proto_goTypes = nil
	file_proto_sensor_proto_depIdxs = nil
}
